twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        allArticles: '@App\Twig\ArticleExtension'
        allCategories: '@App\Twig\CategoryExtension'

when@test:
    twig:
        strict_variables: true
