twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        articles: '@App\Twig\ArticleExtension'
        categories: '@App\Twig\CategoryExtension'

when@test:
    twig:
        strict_variables: true
